# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            depressiverobot.tk
tagline:          'a Netzkind`s blog'
description:      'A blog full of stuff around my PhD thesis, (semantic) developer things, gadgets and everything else I`m interested in.'
url:              http://depressiverobot.tk
baseurl:          '/'
paginate:         5

author:
  name:           'Marvin Frommhold'
  url:            http://depressiverobot.tk

# Custom vars
#version:          1.0.0

#github:
#  repo:           https://github.com/poole/lanyon
