gems:
  - jekyll-sitemap

# jekyll settings
host: 0.0.0.0
port: 4000

# Build settings
markdown: redcarpet
highlighter: pygments

sass:
  sass_dir: assets/css/_sass

# Site settings
title: "depressiveRobot"
description: "a semantic web developer blog"
# > # this means to ignore newlines until "email:"

#blog logo
logo: "/assets/images/author.png"
# blog cover
cover: "/assets/images/DSC_2775.jpg"

author:
  name: "Marvin Frommhold"
  image: "/assets/images/author.png"
  email: "marvin.frommhold@gmail.com"
  uri: "http://depressiverobot/about/#MarvinFrommhold"
  bio: '<i>"Aufgrund falschen Medienkonsums und Bildungsmangel gibt es in Deutschland immer mehr <b>assipöse</b> Menschen."</i>'

license:
  url: "http://creativecommons.org/licenses/by-nc/4.0/"
  name: "CC BY-NC 4.0 license"

paginate:	10

url: "http://depressiverobot.com" # the base hostname & protocol for your site
baseurl: ""
uri: "http://depressiverobot.com/"

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/depressiveRobot
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_link: "?url="
    share_title: "&amp;text="

  - icon: google-plus
    url: https://google.com/+MarvinFrommhold
    desc: Add me on google+
    share_url: https://plus.google.com/share
    share_link: "?url="
    share_title:

  - icon: github
    url: https://github.com/depressiveRobot
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:  rss
    url: /feed.xml
    desc: Subscribe to my feed
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
