# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            depressiverobot.com
tagline:          "a semantic web developer blog"
description:      "A blog full of stuff around my PhD thesis, the adventures as a Semantic Web developer and everything else I'm interested in."
url:              http://depressiverobot.com
baseurl:          "/"
paginate:         5

author:
  name:           "Marvin Frommhold"
  url:            http://depressiverobot.com/about/