gems:
  - jekyll-sitemap

# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "depressiveRobot"
description: "a semantic web developer blog"
# > # this means to ignore newlines until "email:"

#blog logo
logo: "/assets/images/author.png"
# blog cover
cover: "/assets/images/DSC_2775.jpg"

author:
  name: "Marvin Frommhold"
  image: "/assets/images/author.png"
  email: "marvin.frommhold@gmail.com"
  uri: "http://depressiverobot/about/#MarvinFrommhold"

license:
  url: "http://creativecommons.org/licenses/by-nc/4.0/"
  name: "Creative Commons Attribution-NonCommercial 4.0 International License"

paginate:	10

url: "http://depressiverobot.com" # the base hostname & protocol for your site
baseurl: ""
uri: "http://depressiverobot.com/"

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/depressiveRobot
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: google-plus
    url: https://google.com/+MarvinFrommhold
    desc: Add me on google+
    share_url:
    share_title:
    share_link:

  - icon: github
    url: https://github.com/depressiveRobot
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:  rss
    url: http://depressiverobot.com/feed.xml
    desc: Subscribe to my feed
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
